parameters:
#    stupindle.example.class: BundleLabs\StupindleBundle\Example

services:
#    stupindle.example:
#        class: %stupindle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
